version: '3.9'

services: 
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver 
    container_name: sql_server
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    env_file:
      - .env
#USING GO after single command
